frase = 'curso em video python'
frase2 = '   Aprendenda python  '
print(len(frase))
print(frase[::3])
print(frase[9:21:2])
print(frase.count('o',0 ,14))
print(frase.find('deo'))
print(frase.replace('python', 'android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2.strip())
print(frase2.lstrip())
print(frase2.rstrip())
print(frase.split())
dividido = frase.split()
print(dividido[2] [3])
print('-'.join(frase))
